name: soccer-field-booking
services:
  payment-service:
    container_name: payment-service
    platform: linux/amd64
    image: bintangnugraha/payment-service:1
    ports:
      - "8003:8003"
    env_file:
      - .env