name: soccer-field-booking
services:
  user-service:
    container_name: user-service
    platform: windows/amd64
    # image: bintangnugraha/user-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
